# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d6121954d788e612f19fff014cd815cd719bfc805694d0941745abb88ad4e384cf6921be3b52c54361220fce6388ba16fea65f8b38d4d56dc3b34712c9e0696

test:
  secret_key_base: ff52b562531095e4b034405e082d933f83a9a488080d1be82a09034568388b715a98177c103e3fd6340e5fa409cc97cc6bea9e15ea076119d3a9a5304d62de26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
